namespace Maple.UnityAssistant.Context.UnityMetadata.MethodSignature;

public static class UnityEngine_Rigidbody2D
{
    public const string MONO_AddForceInjected = "UnityEngine.Rigidbody2D::AddForce_Injected";
    public const string MONO_AddForceAtPositionInjected = "UnityEngine.Rigidbody2D::AddForceAtPosition_Injected";
    public const string MONO_AddRelativeForceInjected = "UnityEngine.Rigidbody2D::AddRelativeForce_Injected";
    public const string MONO_AddTorque = "UnityEngine.Rigidbody2D::AddTorque";
    public const string MONO_CastArrayInternalInjected = "UnityEngine.Rigidbody2D::CastArray_Internal_Injected";
    public const string MONO_CastFilteredArrayInternalInjected = "UnityEngine.Rigidbody2D::CastFilteredArray_Internal_Injected";
    public const string MONO_CastFilteredListInternalInjected = "UnityEngine.Rigidbody2D::CastFilteredList_Internal_Injected";
    public const string MONO_CastListInternalInjected = "UnityEngine.Rigidbody2D::CastList_Internal_Injected";
    public const string MONO_DistanceInternalInjected = "UnityEngine.Rigidbody2D::Distance_Internal_Injected";
    public const string MONO_GetAngularDrag = "UnityEngine.Rigidbody2D::get_angularDrag";
    public const string MONO_GetAngularVelocity = "UnityEngine.Rigidbody2D::get_angularVelocity";
    public const string MONO_GetAttachedColliderCount = "UnityEngine.Rigidbody2D::get_attachedColliderCount";
    public const string MONO_GetBodyType = "UnityEngine.Rigidbody2D::get_bodyType";
    public const string MONO_GetCenterOfMassInjected = "UnityEngine.Rigidbody2D::get_centerOfMass_Injected";
    public const string MONO_GetCollisionDetectionMode = "UnityEngine.Rigidbody2D::get_collisionDetectionMode";
    public const string MONO_GetConstraints = "UnityEngine.Rigidbody2D::get_constraints";
    public const string MONO_GetDrag = "UnityEngine.Rigidbody2D::get_drag";
    public const string MONO_GetFixedAngle = "UnityEngine.Rigidbody2D::get_fixedAngle";
    public const string MONO_GetFreezeRotation = "UnityEngine.Rigidbody2D::get_freezeRotation";
    public const string MONO_GetGravityScale = "UnityEngine.Rigidbody2D::get_gravityScale";
    public const string MONO_GetInertia = "UnityEngine.Rigidbody2D::get_inertia";
    public const string MONO_GetInterpolation = "UnityEngine.Rigidbody2D::get_interpolation";
    public const string MONO_GetMass = "UnityEngine.Rigidbody2D::get_mass";
    public const string MONO_GetPositionInjected = "UnityEngine.Rigidbody2D::get_position_Injected";
    public const string MONO_GetRotation = "UnityEngine.Rigidbody2D::get_rotation";
    public const string MONO_GetSharedMaterial = "UnityEngine.Rigidbody2D::get_sharedMaterial";
    public const string MONO_GetSimulated = "UnityEngine.Rigidbody2D::get_simulated";
    public const string MONO_GetSleepMode = "UnityEngine.Rigidbody2D::get_sleepMode";
    public const string MONO_GetUseAutoMass = "UnityEngine.Rigidbody2D::get_useAutoMass";
    public const string MONO_GetUseFullKinematicContacts = "UnityEngine.Rigidbody2D::get_useFullKinematicContacts";
    public const string MONO_GetVelocityInjected = "UnityEngine.Rigidbody2D::get_velocity_Injected";
    public const string MONO_GetWorldCenterOfMassInjected = "UnityEngine.Rigidbody2D::get_worldCenterOfMass_Injected";
    public const string MONO_GetAttachedCollidersArrayInternal = "UnityEngine.Rigidbody2D::GetAttachedCollidersArray_Internal";
    public const string MONO_GetAttachedCollidersListInternal = "UnityEngine.Rigidbody2D::GetAttachedCollidersList_Internal";
    public const string MONO_GetPointInjected = "UnityEngine.Rigidbody2D::GetPoint_Injected";
    public const string MONO_GetPointVelocityInjected = "UnityEngine.Rigidbody2D::GetPointVelocity_Injected";
    public const string MONO_GetRelativePointInjected = "UnityEngine.Rigidbody2D::GetRelativePoint_Injected";
    public const string MONO_GetRelativePointVelocityInjected = "UnityEngine.Rigidbody2D::GetRelativePointVelocity_Injected";
    public const string MONO_GetRelativeVectorInjected = "UnityEngine.Rigidbody2D::GetRelativeVector_Injected";
    public const string MONO_GetShapesInternal = "UnityEngine.Rigidbody2D::GetShapes_Internal";
    public const string MONO_GetVectorInjected = "UnityEngine.Rigidbody2D::GetVector_Injected";
    public const string MONO_IsAwake = "UnityEngine.Rigidbody2D::IsAwake";
    public const string MONO_IsSleeping = "UnityEngine.Rigidbody2D::IsSleeping";
    public const string MONO_IsTouching = "UnityEngine.Rigidbody2D::IsTouching";
    public const string MONO_IsTouchingAnyColliderWithFilterInternalInjected = "UnityEngine.Rigidbody2D::IsTouching_AnyColliderWithFilter_Internal_Injected";
    public const string MONO_IsTouchingOtherColliderWithFilterInternalInjected = "UnityEngine.Rigidbody2D::IsTouching_OtherColliderWithFilter_Internal_Injected";
    public const string MONO_IsTouchingLayers = "UnityEngine.Rigidbody2D::IsTouchingLayers";
    public const string MONO_MovePositionInjected = "UnityEngine.Rigidbody2D::MovePosition_Injected";
    public const string MONO_MoveRotationAngle = "UnityEngine.Rigidbody2D::MoveRotation_Angle";
    public const string MONO_MoveRotationQuaternionInjected = "UnityEngine.Rigidbody2D::MoveRotation_Quaternion_Injected";
    public const string MONO_OverlapColliderArrayInternalInjected = "UnityEngine.Rigidbody2D::OverlapColliderArray_Internal_Injected";
    public const string MONO_OverlapColliderListInternalInjected = "UnityEngine.Rigidbody2D::OverlapColliderList_Internal_Injected";
    public const string MONO_OverlapPointInjected = "UnityEngine.Rigidbody2D::OverlapPoint_Injected";
    public const string MONO_SetAngularDrag = "UnityEngine.Rigidbody2D::set_angularDrag";
    public const string MONO_SetAngularVelocity = "UnityEngine.Rigidbody2D::set_angularVelocity";
    public const string MONO_SetBodyType = "UnityEngine.Rigidbody2D::set_bodyType";
    public const string MONO_SetCenterOfMassInjected = "UnityEngine.Rigidbody2D::set_centerOfMass_Injected";
    public const string MONO_SetCollisionDetectionMode = "UnityEngine.Rigidbody2D::set_collisionDetectionMode";
    public const string MONO_SetConstraints = "UnityEngine.Rigidbody2D::set_constraints";
    public const string MONO_SetDrag = "UnityEngine.Rigidbody2D::set_drag";
    public const string MONO_SetFixedAngle = "UnityEngine.Rigidbody2D::set_fixedAngle";
    public const string MONO_SetFreezeRotation = "UnityEngine.Rigidbody2D::set_freezeRotation";
    public const string MONO_SetGravityScale = "UnityEngine.Rigidbody2D::set_gravityScale";
    public const string MONO_SetInertia = "UnityEngine.Rigidbody2D::set_inertia";
    public const string MONO_SetInterpolation = "UnityEngine.Rigidbody2D::set_interpolation";
    public const string MONO_SetMass = "UnityEngine.Rigidbody2D::set_mass";
    public const string MONO_SetPositionInjected = "UnityEngine.Rigidbody2D::set_position_Injected";
    public const string MONO_SetRotation = "UnityEngine.Rigidbody2D::set_rotation";
    public const string MONO_SetSharedMaterial = "UnityEngine.Rigidbody2D::set_sharedMaterial";
    public const string MONO_SetSimulated = "UnityEngine.Rigidbody2D::set_simulated";
    public const string MONO_SetSleepMode = "UnityEngine.Rigidbody2D::set_sleepMode";
    public const string MONO_SetUseAutoMass = "UnityEngine.Rigidbody2D::set_useAutoMass";
    public const string MONO_SetUseFullKinematicContacts = "UnityEngine.Rigidbody2D::set_useFullKinematicContacts";
    public const string MONO_SetVelocityInjected = "UnityEngine.Rigidbody2D::set_velocity_Injected";
    public const string MONO_SetDragBehaviour = "UnityEngine.Rigidbody2D::SetDragBehaviour";
    public const string MONO_SetRotationAngle = "UnityEngine.Rigidbody2D::SetRotation_Angle";
    public const string MONO_SetRotationQuaternionInjected = "UnityEngine.Rigidbody2D::SetRotation_Quaternion_Injected";
    public const string MONO_Sleep = "UnityEngine.Rigidbody2D::Sleep";
    public const string MONO_WakeUp = "UnityEngine.Rigidbody2D::WakeUp";

    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public unsafe readonly partial struct Ptr_UnityEngine_Rigidbody2D : MonoGameAssistant.MetadataExtensions.MetadataGenerator.IPtrMetadata
    {
        [System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.SysInt)]
        private readonly nint m_Pointer;

        public Ptr_UnityEngine_Rigidbody2D(nint ptr) { m_Pointer = ptr; }

        public nint Ptr => m_Pointer;

        public static implicit operator Ptr_UnityEngine_Rigidbody2D(nint ptr) => new Ptr_UnityEngine_Rigidbody2D(ptr);
        public static implicit operator nint(Ptr_UnityEngine_Rigidbody2D ptr) => ptr.m_Pointer;
        public static implicit operator bool(Ptr_UnityEngine_Rigidbody2D ptr) => ptr.m_Pointer != nint.Zero;

        public override string ToString() => m_Pointer.ToString("X8");
    }
    public const string IL2CPP_AddForce_Injected = "UnityEngine.Rigidbody2D::AddForce_Injected(UnityEngine.Vector2&,UnityEngine.ForceMode2D)";
    public const string IL2CPP_AddForceAtPosition_Injected = "UnityEngine.Rigidbody2D::AddForceAtPosition_Injected(UnityEngine.Vector2&,UnityEngine.Vector2&,UnityEngine.ForceMode2D)";
    public const string IL2CPP_AddRelativeForce_Injected = "UnityEngine.Rigidbody2D::AddRelativeForce_Injected(UnityEngine.Vector2&,UnityEngine.ForceMode2D)";
    public const string IL2CPP_AddTorque = "UnityEngine.Rigidbody2D::AddTorque(System.Single,UnityEngine.ForceMode2D)";
    public const string IL2CPP_CastArray_Internal_Injected = "UnityEngine.Rigidbody2D::CastArray_Internal_Injected(UnityEngine.Vector2&,System.Single,UnityEngine.RaycastHit2D[])";
    public const string IL2CPP_CastFilteredArray_Internal_Injected = "UnityEngine.Rigidbody2D::CastFilteredArray_Internal_Injected(UnityEngine.Vector2&,System.Single,UnityEngine.ContactFilter2D&,UnityEngine.RaycastHit2D[])";
    public const string IL2CPP_CastFilteredList_Internal_Injected = "UnityEngine.Rigidbody2D::CastFilteredList_Internal_Injected(UnityEngine.Vector2&,System.Single,UnityEngine.ContactFilter2D&,System.Collections.Generic.List`1<UnityEngine.RaycastHit2D>)";
    public const string IL2CPP_CastList_Internal_Injected = "UnityEngine.Rigidbody2D::CastList_Internal_Injected(UnityEngine.Vector2&,System.Single,System.Collections.Generic.List`1<UnityEngine.RaycastHit2D>)";
    public const string IL2CPP_Distance_Internal_Injected = "UnityEngine.Rigidbody2D::Distance_Internal_Injected(UnityEngine.Collider2D,UnityEngine.ColliderDistance2D&)";
    public const string IL2CPP_get_angularDrag = "UnityEngine.Rigidbody2D::get_angularDrag()";
    public const string IL2CPP_get_angularVelocity = "UnityEngine.Rigidbody2D::get_angularVelocity()";
    public const string IL2CPP_get_attachedColliderCount = "UnityEngine.Rigidbody2D::get_attachedColliderCount()";
    public const string IL2CPP_get_bodyType = "UnityEngine.Rigidbody2D::get_bodyType()";
    public const string IL2CPP_get_centerOfMass_Injected = "UnityEngine.Rigidbody2D::get_centerOfMass_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_get_collisionDetectionMode = "UnityEngine.Rigidbody2D::get_collisionDetectionMode()";
    public const string IL2CPP_get_constraints = "UnityEngine.Rigidbody2D::get_constraints()";
    public const string IL2CPP_get_drag = "UnityEngine.Rigidbody2D::get_drag()";
    public const string IL2CPP_get_fixedAngle = "UnityEngine.Rigidbody2D::get_fixedAngle()";
    public const string IL2CPP_get_freezeRotation = "UnityEngine.Rigidbody2D::get_freezeRotation()";
    public const string IL2CPP_get_gravityScale = "UnityEngine.Rigidbody2D::get_gravityScale()";
    public const string IL2CPP_get_inertia = "UnityEngine.Rigidbody2D::get_inertia()";
    public const string IL2CPP_get_interpolation = "UnityEngine.Rigidbody2D::get_interpolation()";
    public const string IL2CPP_get_mass = "UnityEngine.Rigidbody2D::get_mass()";
    public const string IL2CPP_get_position_Injected = "UnityEngine.Rigidbody2D::get_position_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_get_rotation = "UnityEngine.Rigidbody2D::get_rotation()";
    public const string IL2CPP_get_sharedMaterial = "UnityEngine.Rigidbody2D::get_sharedMaterial()";
    public const string IL2CPP_get_simulated = "UnityEngine.Rigidbody2D::get_simulated()";
    public const string IL2CPP_get_sleepMode = "UnityEngine.Rigidbody2D::get_sleepMode()";
    public const string IL2CPP_get_useAutoMass = "UnityEngine.Rigidbody2D::get_useAutoMass()";
    public const string IL2CPP_get_useFullKinematicContacts = "UnityEngine.Rigidbody2D::get_useFullKinematicContacts()";
    public const string IL2CPP_get_velocity_Injected = "UnityEngine.Rigidbody2D::get_velocity_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_get_worldCenterOfMass_Injected = "UnityEngine.Rigidbody2D::get_worldCenterOfMass_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_GetAttachedCollidersArray_Internal = "UnityEngine.Rigidbody2D::GetAttachedCollidersArray_Internal(UnityEngine.Collider2D[])";
    public const string IL2CPP_GetAttachedCollidersList_Internal = "UnityEngine.Rigidbody2D::GetAttachedCollidersList_Internal(System.Collections.Generic.List`1<UnityEngine.Collider2D>)";
    public const string IL2CPP_GetPoint_Injected = "UnityEngine.Rigidbody2D::GetPoint_Injected(UnityEngine.Vector2&,UnityEngine.Vector2&)";
    public const string IL2CPP_GetPointVelocity_Injected = "UnityEngine.Rigidbody2D::GetPointVelocity_Injected(UnityEngine.Vector2&,UnityEngine.Vector2&)";
    public const string IL2CPP_GetRelativePoint_Injected = "UnityEngine.Rigidbody2D::GetRelativePoint_Injected(UnityEngine.Vector2&,UnityEngine.Vector2&)";
    public const string IL2CPP_GetRelativePointVelocity_Injected = "UnityEngine.Rigidbody2D::GetRelativePointVelocity_Injected(UnityEngine.Vector2&,UnityEngine.Vector2&)";
    public const string IL2CPP_GetRelativeVector_Injected = "UnityEngine.Rigidbody2D::GetRelativeVector_Injected(UnityEngine.Vector2&,UnityEngine.Vector2&)";
    public const string IL2CPP_GetShapes_Internal = "UnityEngine.Rigidbody2D::GetShapes_Internal(UnityEngine.PhysicsShapeGroup2D/GroupState&)";
    public const string IL2CPP_GetVector_Injected = "UnityEngine.Rigidbody2D::GetVector_Injected(UnityEngine.Vector2&,UnityEngine.Vector2&)";
    public const string IL2CPP_IsAwake = "UnityEngine.Rigidbody2D::IsAwake()";
    public const string IL2CPP_IsSleeping = "UnityEngine.Rigidbody2D::IsSleeping()";
    public const string IL2CPP_IsTouching = "UnityEngine.Rigidbody2D::IsTouching(UnityEngine.Collider2D)";
    public const string IL2CPP_IsTouching_AnyColliderWithFilter_Internal_Injected = "UnityEngine.Rigidbody2D::IsTouching_AnyColliderWithFilter_Internal_Injected(UnityEngine.ContactFilter2D&)";
    public const string IL2CPP_IsTouching_OtherColliderWithFilter_Internal_Injected = "UnityEngine.Rigidbody2D::IsTouching_OtherColliderWithFilter_Internal_Injected(UnityEngine.Collider2D,UnityEngine.ContactFilter2D&)";
    public const string IL2CPP_IsTouchingLayers = "UnityEngine.Rigidbody2D::IsTouchingLayers(System.Int32)";
    public const string IL2CPP_MovePosition_Injected = "UnityEngine.Rigidbody2D::MovePosition_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_MoveRotation_Angle = "UnityEngine.Rigidbody2D::MoveRotation_Angle(System.Single)";
    public const string IL2CPP_MoveRotation_Quaternion_Injected = "UnityEngine.Rigidbody2D::MoveRotation_Quaternion_Injected(UnityEngine.Quaternion&)";
    public const string IL2CPP_OverlapColliderArray_Internal_Injected = "UnityEngine.Rigidbody2D::OverlapColliderArray_Internal_Injected(UnityEngine.ContactFilter2D&,UnityEngine.Collider2D[])";
    public const string IL2CPP_OverlapColliderList_Internal_Injected = "UnityEngine.Rigidbody2D::OverlapColliderList_Internal_Injected(UnityEngine.ContactFilter2D&,System.Collections.Generic.List`1<UnityEngine.Collider2D>)";
    public const string IL2CPP_OverlapPoint_Injected = "UnityEngine.Rigidbody2D::OverlapPoint_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_set_angularDrag = "UnityEngine.Rigidbody2D::set_angularDrag(System.Single)";
    public const string IL2CPP_set_angularVelocity = "UnityEngine.Rigidbody2D::set_angularVelocity(System.Single)";
    public const string IL2CPP_set_bodyType = "UnityEngine.Rigidbody2D::set_bodyType(UnityEngine.RigidbodyType2D)";
    public const string IL2CPP_set_centerOfMass_Injected = "UnityEngine.Rigidbody2D::set_centerOfMass_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_set_collisionDetectionMode = "UnityEngine.Rigidbody2D::set_collisionDetectionMode(UnityEngine.CollisionDetectionMode2D)";
    public const string IL2CPP_set_constraints = "UnityEngine.Rigidbody2D::set_constraints(UnityEngine.RigidbodyConstraints2D)";
    public const string IL2CPP_set_drag = "UnityEngine.Rigidbody2D::set_drag(System.Single)";
    public const string IL2CPP_set_fixedAngle = "UnityEngine.Rigidbody2D::set_fixedAngle(System.Boolean)";
    public const string IL2CPP_set_freezeRotation = "UnityEngine.Rigidbody2D::set_freezeRotation(System.Boolean)";
    public const string IL2CPP_set_gravityScale = "UnityEngine.Rigidbody2D::set_gravityScale(System.Single)";
    public const string IL2CPP_set_inertia = "UnityEngine.Rigidbody2D::set_inertia(System.Single)";
    public const string IL2CPP_set_interpolation = "UnityEngine.Rigidbody2D::set_interpolation(UnityEngine.RigidbodyInterpolation2D)";
    public const string IL2CPP_set_mass = "UnityEngine.Rigidbody2D::set_mass(System.Single)";
    public const string IL2CPP_set_position_Injected = "UnityEngine.Rigidbody2D::set_position_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_set_rotation = "UnityEngine.Rigidbody2D::set_rotation(System.Single)";
    public const string IL2CPP_set_sharedMaterial = "UnityEngine.Rigidbody2D::set_sharedMaterial(UnityEngine.PhysicsMaterial2D)";
    public const string IL2CPP_set_simulated = "UnityEngine.Rigidbody2D::set_simulated(System.Boolean)";
    public const string IL2CPP_set_sleepMode = "UnityEngine.Rigidbody2D::set_sleepMode(UnityEngine.RigidbodySleepMode2D)";
    public const string IL2CPP_set_useAutoMass = "UnityEngine.Rigidbody2D::set_useAutoMass(System.Boolean)";
    public const string IL2CPP_set_useFullKinematicContacts = "UnityEngine.Rigidbody2D::set_useFullKinematicContacts(System.Boolean)";
    public const string IL2CPP_set_velocity_Injected = "UnityEngine.Rigidbody2D::set_velocity_Injected(UnityEngine.Vector2&)";
    public const string IL2CPP_SetDragBehaviour = "UnityEngine.Rigidbody2D::SetDragBehaviour(System.Boolean)";
    public const string IL2CPP_SetRotation_Angle = "UnityEngine.Rigidbody2D::SetRotation_Angle(System.Single)";
    public const string IL2CPP_SetRotation_Quaternion_Injected = "UnityEngine.Rigidbody2D::SetRotation_Quaternion_Injected(UnityEngine.Quaternion&)";
    public const string IL2CPP_Sleep = "UnityEngine.Rigidbody2D::Sleep()";
    public const string IL2CPP_WakeUp = "UnityEngine.Rigidbody2D::WakeUp()";
}

